### ISSUE TITLE
not detecting Adobe CLA signed 

### ISSUE THREAD

**Issue by armanism24** [adobe/cla-bot#140] opened 2021-07-06 10:43 UTC
Hi team,
Recently, I made changes in Magento documentation and submitted a pull request (Update nginx.md) on GitHub.
I have already submitted the "Adobe CLA" but still, this is showing not signed? 
Please check this issue.

**Comment by josh-hadley** [comment] 2022-09-26 22:05
@armanism24 I realize this issue is over 1 year old; I'm doing some long-overdue maintenance and wanted to respond for the benefit of others and close this out. If you haven't gotten this sorted out yet, please re-try submitting the CLA and ensure that:
 - you have the correct GitHub username (with no "@" in front, just the plain username, not email) in the GitHub username field
 - you have your full, correct, primary email associated with your GitHub account in the email field

There are intermittent failures caused by network blips and other anomalies, but the vast majority of "not detecting signed CLA" problems are caused by the above 2 items.

**Closed** 2022-09-26 22:05 UTC
